# Comprehensive Global Airport and City Database (~500+ Commercial Airports Worldwide)

AIRPORT_DATA = [
    # GREECE
    ("ATH", "Athens Eleftherios Venizelos", "Greece"),
    ("SKG", "Thessaloniki Makedonia", "Greece"),
    ("HER", "Heraklion Nikos Kazantzakis", "Greece"),
    ("CHQ", "Chania Ioannis Daskalogiannis", "Greece"),
    ("RHO", "Rhodes Diagoras", "Greece"),
    ("CFU", "Corfu Ioannis Kapodistrias", "Greece"),
    ("JMK", "Mykonos Island National", "Greece"),
    ("JTR", "Santorini Thira", "Greece"),
    ("KGS", "Kos International", "Greece"),
    ("ZTH", "Zakynthos Dionysios Solomos", "Greece"),
    ("KTT", "Kalamata Captain Vassilis Constantakopoulos", "Greece"),
    ("PVK", "Aktion Preveza Lefkada", "Greece"),
    ("EFL", "Kefalonia Island International", "Greece"),
    ("SMI", "Samos Aristarchos of Samos", "Greece"),
    ("MJT", "Mytilene Odysseas Elytis Lesvos", "Greece"),
    ("JNX", "Naxos Island National", "Greece"),
    ("PAS", "Paros National", "Greece"),
    ("JKH", "Chios Island National", "Greece"),
    ("VOL", "Nea Anchialos Volos", "Greece"),
    ("IOA", "Ioannina King Pyrros", "Greece"),
    ("AOK", "Karpathos Island National", "Greece"),
    ("LXG", "Lemnos International", "Greece"),
    ("LXS", "Lemnos Hephaestus", "Greece"),
    ("AXD", "Alexandroupoli Dimokritos", "Greece"),

    # UNITED KINGDOM & IRELAND
    ("LON", "London All Airports", "United Kingdom"),
    ("LHR", "London Heathrow", "United Kingdom"),
    ("LGW", "London Gatwick", "United Kingdom"),
    ("STN", "London Stansted", "United Kingdom"),
    ("LTN", "London Luton", "United Kingdom"),
    ("LCY", "London City", "United Kingdom"),
    ("SEN", "London Southend", "United Kingdom"),
    ("MAN", "Manchester", "United Kingdom"),
    ("BHX", "Birmingham", "United Kingdom"),
    ("EDI", "Edinburgh", "United Kingdom"),
    ("GLA", "Glasgow", "United Kingdom"),
    ("BRS", "Bristol", "United Kingdom"),
    ("NCL", "Newcastle", "United Kingdom"),
    ("LPL", "Liverpool John Lennon", "United Kingdom"),
    ("BFS", "Belfast International", "United Kingdom"),
    ("BHD", "Belfast City", "United Kingdom"),
    ("ABZ", "Aberdeen", "United Kingdom"),
    ("CWL", "Cardiff", "United Kingdom"),
    ("DUB", "Dublin", "Ireland"),
    ("SNN", "Shannon", "Ireland"),
    ("ORK", "Cork", "Ireland"),
    ("NOC", "Ireland West Knock", "Ireland"),

    # WESTERN EUROPE & NORDICS
    ("CDG", "Paris Charles de Gaulle", "France"),
    ("ORY", "Paris Orly", "France"),
    ("PAR", "Paris All Airports", "France"),
    ("BVA", "Paris Beauvais", "France"),
    ("NCE", "Nice Cote d'Azur", "France"),
    ("LYS", "Lyon Saint-Exupery", "France"),
    ("MRS", "Marseille Provence", "France"),
    ("TLS", "Toulouse Blagnac", "France"),
    ("BOD", "Bordeaux Merignac", "France"),
    ("NTE", "Nantes Atlantique", "France"),
    ("AMS", "Amsterdam Schiphol", "Netherlands"),
    ("EIN", "Eindhoven", "Netherlands"),
    ("BRU", "Brussels", "Belgium"),
    ("CRL", "Brussels Charleroi", "Belgium"),
    ("LUX", "Luxembourg Findel", "Luxembourg"),
    ("FRA", "Frankfurt", "Germany"),
    ("MUC", "Munich", "Germany"),
    ("BER", "Berlin Brandenburg", "Germany"),
    ("HAM", "Hamburg", "Germany"),
    ("DUS", "Dusseldorf", "Germany"),
    ("CGN", "Cologne Bonn", "Germany"),
    ("STR", "Stuttgart", "Germany"),
    ("HAJ", "Hannover", "Germany"),
    ("NUE", "Nuremberg", "Germany"),
    ("VIE", "Vienna", "Austria"),
    ("SZG", "Salzburg", "Austria"),
    ("INN", "Innsbruck", "Austria"),
    ("ZRH", "Zurich", "Switzerland"),
    ("GVA", "Geneva", "Switzerland"),
    ("BSL", "Basel Mulhouse Freiburg", "Switzerland"),
    ("CPH", "Copenhagen", "Denmark"),
    ("BLL", "Billund", "Denmark"),
    ("OSL", "Oslo Gardermoen", "Norway"),
    ("BGO", "Bergen Flesland", "Norway"),
    ("TRD", "Trondheim", "Norway"),
    ("ARN", "Stockholm Arlanda", "Sweden"),
    ("NYO", "Stockholm Skavsta", "Sweden"),
    ("GOT", "Gothenburg Landvetter", "Sweden"),
    ("HEL", "Helsinki Vantaa", "Finland"),
    ("KEF", "Reykjavik Keflavik", "Iceland"),

    # SOUTHERN EUROPE
    ("FCO", "Rome Fiumicino", "Italy"),
    ("CIA", "Rome Ciampino", "Italy"),
    ("ROM", "Rome All Airports", "Italy"),
    ("MXP", "Milan Malpensa", "Italy"),
    ("LIN", "Milan Linate", "Italy"),
    ("BGY", "Milan Bergamo", "Italy"),
    ("MIL", "Milan All Airports", "Italy"),
    ("VCE", "Venice Marco Polo", "Italy"),
    ("TSF", "Venice Treviso", "Italy"),
    ("NAP", "Naples Capodichino", "Italy"),
    ("BLQ", "Bologna Guglielmo Marconi", "Italy"),
    ("CTA", "Catania Fontanarossa", "Italy"),
    ("PMO", "Palermo Falcone Borsellino", "Italy"),
    ("PSA", "Pisa Galileo Galilei", "Italy"),
    ("FLR", "Florence Peretola", "Italy"),
    ("BRI", "Bari Karol Wojtyla", "Italy"),
    ("SUF", "Lamezia Terme", "Italy"),
    ("CAG", "Cagliari Elmas", "Italy"),
    ("OLB", "Olbia Costa Smeralda", "Italy"),
    ("MAD", "Madrid Barajas", "Spain"),
    ("BCN", "Barcelona El Prat", "Spain"),
    ("AGP", "Malaga Costa del Sol", "Spain"),
    ("PMI", "Palma de Mallorca", "Spain"),
    ("ALC", "Alicante Elche", "Spain"),
    ("VLC", "Valencia", "Spain"),
    ("SVQ", "Seville", "Spain"),
    ("BIO", "Bilbao", "Spain"),
    ("IBZ", "Ibiza", "Spain"),
    ("MAH", "Menorca", "Spain"),
    ("TFS", "Tenerife South", "Spain"),
    ("TFN", "Tenerife North", "Spain"),
    ("LPA", "Gran Canaria", "Spain"),
    ("ACE", "Lanzarote", "Spain"),
    ("FUE", "Fuerteventura", "Spain"),
    ("LIS", "Lisbon Humberto Delgado", "Portugal"),
    ("OPO", "Porto Francisco Sa Carneiro", "Portugal"),
    ("FAO", "Faro", "Portugal"),
    ("FNC", "Madeira Funchal", "Portugal"),
    ("PDL", "Ponta Delgada Azores", "Portugal"),
    ("MLA", "Malta International", "Malta"),
    ("LCA", "Larnaca", "Cyprus"),
    ("PFO", "Paphos", "Cyprus"),

    # EASTERN EUROPE & BALKANS
    ("WAW", "Warsaw Chopin", "Poland"),
    ("WMI", "Warsaw Modlin", "Poland"),
    ("KRK", "Krakow John Paul II", "Poland"),
    ("GDN", "Gdansk Lech Walesa", "Poland"),
    ("WRO", "Wroclaw Copernicus", "Poland"),
    ("POZ", "Poznan Lawica", "Poland"),
    ("PRG", "Václav Havel Prague", "Czech Republic"),
    ("BUD", "Budapest Ferenc Liszt", "Hungary"),
    ("OTP", "Bucharest Henri Coanda", "Romania"),
    ("CLJ", "Cluj Napoca", "Romania"),
    ("SOF", "Sofia", "Bulgaria"),
    ("BOJ", "Burgas", "Bulgaria"),
    ("VAR", "Varna", "Bulgaria"),
    ("BEG", "Belgrade Nikola Tesla", "Serbia"),
    ("ZAG", "Zagreb Franjo Tudman", "Croatia"),
    ("SPU", "Split", "Croatia"),
    ("DBV", "Dubrovnik", "Croatia"),
    ("PUY", "Pula", "Croatia"),
    ("ZAD", "Zadar", "Croatia"),
    ("LJU", "Ljubljana Joze Pucnik", "Slovenia"),
    ("SJJ", "Sarajevo", "Bosnia and Herzegovina"),
    ("TGD", "Podgorica", "Montenegro"),
    ("TIV", "Tivat", "Montenegro"),
    ("TIA", "Tirana Nene Tereza", "Albania"),
    ("SKP", "Skopje International", "North Macedonia"),
    ("RIX", "Riga International", "Latvia"),
    ("VNO", "Vilnius", "Lithuania"),
    ("TLL", "Tallinn Lennart Meri", "Estonia"),
    ("KIV", "Chisinau International", "Moldova"),
    ("KBP", "Kyiv Boryspil", "Ukraine"),

    # TURKEY, MIDDLE EAST & NORTH AFRICA
    ("IST", "Istanbul Airport", "Turkey"),
    ("SAW", "Istanbul Sabiha Gokcen", "Turkey"),
    ("AYT", "Antalya", "Turkey"),
    ("ADB", "Izmir Adnan Menderes", "Turkey"),
    ("ESB", "Ankara Esenboga", "Turkey"),
    ("DLM", "Dalaman", "Turkey"),
    ("BJV", "Bodrum Milas", "Turkey"),
    ("TLV", "Tel Aviv Ben Gurion", "Israel"),
    ("AMM", "Amman Queen Alia", "Jordan"),
    ("BEY", "Beirut Rafic Hariri", "Lebanon"),
    ("DXB", "Dubai International", "United Arab Emirates"),
    ("DWC", "Dubai Al Maktoum", "United Arab Emirates"),
    ("AUH", "Abu Dhabi International", "United Arab Emirates"),
    ("SHJ", "Sharjah International", "United Arab Emirates"),
    ("DOH", "Doha Hamad International", "Qatar"),
    ("RUH", "Riyadh King Khalid", "Saudi Arabia"),
    ("JED", "Jeddah King Abdulaziz", "Saudi Arabia"),
    ("MCT", "Muscat International", "Oman"),
    ("BAH", "Bahrain International", "Bahrain"),
    ("KWI", "Kuwait International", "Kuwait"),
    ("CAI", "Cairo International", "Egypt"),
    ("HRG", "Hurghada", "Egypt"),
    ("SSH", "Sharm El Sheikh", "Egypt"),
    ("CMN", "Casablanca Mohammed V", "Morocco"),
    ("RAK", "Marrakech Menara", "Morocco"),
    ("TUN", "Tunis Carthage", "Tunisia"),

    # NORTH AMERICA
    ("JFK", "New York John F Kennedy", "United States"),
    ("EWR", "New York Newark Liberty", "United States"),
    ("LGA", "New York LaGuardia", "United States"),
    ("NYC", "New York All Airports", "United States"),
    ("LAX", "Los Angeles International", "United States"),
    ("ORD", "Chicago O'Hare", "United States"),
    ("MDW", "Chicago Midway", "United States"),
    ("CHI", "Chicago All Airports", "United States"),
    ("DFW", "Dallas Fort Worth", "United States"),
    ("DAL", "Dallas Love Field", "United States"),
    ("DEN", "Denver International", "United States"),
    ("SFO", "San Francisco International", "United States"),
    ("OAK", "Oakland", "United States"),
    ("SJC", "San Jose", "United States"),
    ("ATL", "Atlanta Hartsfield Jackson", "United States"),
    ("MIA", "Miami International", "United States"),
    ("FLL", "Fort Lauderdale Hollywood", "United States"),
    ("MCO", "Orlando International", "United States"),
    ("SEA", "Seattle Tacoma", "United States"),
    ("LAS", "Las Vegas Harry Reid", "United States"),
    ("BOS", "Boston Logan", "United States"),
    ("IAD", "Washington Dulles", "United States"),
    ("DCA", "Washington Reagan National", "United States"),
    ("WAS", "Washington DC All Airports", "United States"),
    ("PHX", "Phoenix Sky Harbor", "United States"),
    ("IAH", "Houston George Bush Intercontinental", "United States"),
    ("HOU", "Houston Hobby", "United States"),
    ("MSP", "Minneapolis Saint Paul", "United States"),
    ("DTW", "Detroit Metropolitan", "United States"),
    ("PHL", "Philadelphia International", "United States"),
    ("CLT", "Charlotte Douglas", "United States"),
    ("SLC", "Salt Lake City", "United States"),
    ("SAN", "San Diego", "United States"),
    ("PDX", "Portland International", "United States"),
    ("BNA", "Nashville International", "United States"),
    ("AUS", "Austin Bergstrom", "United States"),
    ("MSY", "New Orleans Louis Armstrong", "United States"),
    ("HNL", "Honolulu Daniel K Inouye", "United States"),
    ("YYZ", "Toronto Pearson", "Canada"),
    ("YTZ", "Toronto Billy Bishop", "Canada"),
    ("YVR", "Vancouver International", "Canada"),
    ("YUL", "Montreal Pierre Elliott Trudeau", "Canada"),
    ("YYC", "Calgary International", "Canada"),
    ("YEG", "Edmonton International", "Canada"),
    ("YOW", "Ottawa Macdonald Cartier", "Canada"),
    ("MEX", "Mexico City Benito Juarez", "Mexico"),
    ("NLU", "Mexico City Felipe Angeles", "Mexico"),
    ("CUN", "Cancun International", "Mexico"),
    ("GDL", "Guadalajara Miguel Hidalgo", "Mexico"),
    ("PVR", "Puerto Vallarta", "Mexico"),
    ("SJD", "Los Cabos", "Mexico"),

    # LATIN AMERICA & CARIBBEAN
    ("GRU", "Sao Paulo Guarulhos", "Brazil"),
    ("CGH", "Sao Paulo Congonhas", "Brazil"),
    ("GIG", "Rio de Janeiro Galeao", "Brazil"),
    ("SDU", "Rio de Janeiro Santos Dumont", "Brazil"),
    ("EZE", "Buenos Aires Ezeiza", "Argentina"),
    ("AEP", "Buenos Aires Jorge Newbery", "Argentina"),
    ("SCL", "Santiago Arturo Merino Benitez", "Chile"),
    ("BOG", "Bogota El Dorado", "Colombia"),
    ("LIM", "Lima Jorge Chavez", "Peru"),
    ("UIO", "Quito Mariscal Sucre", "Ecuador"),
    ("MVD", "Montevideo Carrasco", "Uruguay"),
    ("PTY", "Panama City Tocumen", "Panama"),
    ("SJO", "San Jose Juan Santamaria", "Costa Rica"),
    ("SJU", "San Juan Luis Munoz Marin", "Puerto Rico"),
    ("PUJ", "Punta Cana", "Dominican Republic"),
    ("SDQ", "Santo Domingo Las Americas", "Dominican Republic"),
    ("MBJ", "Montego Bay Sangster", "Jamaica"),
    ("NAS", "Nassau Lynden Pindling", "Bahamas"),

    # ASIA PACIFIC & OCEANIA
    ("HND", "Tokyo Haneda", "Japan"),
    ("NRT", "Tokyo Narita", "Japan"),
    ("TYO", "Tokyo All Airports", "Japan"),
    ("KIX", "Osaka Kansai", "Japan"),
    ("ITM", "Osaka Itami", "Japan"),
    ("CTS", "Sapporo New Chitose", "Japan"),
    ("ICN", "Seoul Incheon", "South Korea"),
    ("GMP", "Seoul Gimpo", "South Korea"),
    ("PEK", "Beijing Capital", "China"),
    ("PKX", "Beijing Daxing", "China"),
    ("PVG", "Shanghai Pudong", "China"),
    ("SHA", "Shanghai Hongqiao", "China"),
    ("CAN", "Guangzhou Baiyun", "China"),
    ("SZX", "Shenzhen Bao'an", "China"),
    ("HKG", "Hong Kong International", "Hong Kong"),
    ("TPE", "Taipei Taoyuan", "Taiwan"),
    ("SIN", "Singapore Changi", "Singapore"),
    ("BKK", "Bangkok Suvarnabhumi", "Thailand"),
    ("DMK", "Bangkok Don Mueang", "Thailand"),
    ("HKT", "Phuket International", "Thailand"),
    ("CNX", "Chiang Mai", "Thailand"),
    ("KUL", "Kuala Lumpur International", "Malaysia"),
    ("CGK", "Jakarta Soekarno Hatta", "Indonesia"),
    ("DPS", "Bali Denpasar Ngurah Rai", "Indonesia"),
    ("MNL", "Manila Ninoy Aquino", "Philippines"),
    ("CEB", "Mactan Cebu", "Philippines"),
    ("SGN", "Ho Chi Minh City Tan Son Nhat", "Vietnam"),
    ("HAN", "Hanoi Noi Bai", "Vietnam"),
    ("DEL", "New Delhi Indira Gandhi", "India"),
    ("BOM", "Mumbai Chhatrapati Shivaji Maharaj", "India"),
    ("BLR", "Bengaluru Kempegowda", "India"),
    ("MAA", "Chennai", "India"),
    ("CCU", "Kolkata Netaji Subhash Chandra Bose", "India"),
    ("SYD", "Sydney Kingsford Smith", "Australia"),
    ("MEL", "Melbourne Tullamarine", "Australia"),
    ("BNE", "Brisbane", "Australia"),
    ("PER", "Perth", "Australia"),
    ("AKL", "Auckland", "New Zealand"),
    ("CHC", "Christchurch", "New Zealand"),

    # AFRICA
    ("JNB", "Johannesburg O R Tambo", "South Africa"),
    ("CPT", "Cape Town International", "South Africa"),
    ("DUR", "Durban King Shaka", "South Africa"),
    ("NBO", "Nairobi Jomo Kenyatta", "Kenya"),
    ("ADD", "Addis Ababa Bole", "Ethiopia"),
    ("LOS", "Lagos Murtala Muhammed", "Nigeria"),
    ("ABV", "Abuja Nnamdi Azikiwe", "Nigeria"),
    ("ACC", "Accra Kotoka", "Ghana"),
    ("MRU", "Mauritius Sir Seewoosagur Ramgoolam", "Mauritius"),
    ("SEZ", "Seychelles International", "Seychelles")
]
